import type {
  SeedExercise,
  SeedExerciseCategory,
  SeedExerciseMedia,
  SeedExerciseSetLog,
  SeedWorkoutAssignment,
  SeedWorkoutFeedback,
  SeedWorkoutSession,
  SeedWorkoutTemplate,
  SeedWorkoutTemplateExercise,
} from "./schema.js";

export const seedTimestamps = {
  assignedOn: "2026-01-06",
  createdAt: "2026-01-01T00:00:00.000Z",
  feedbackSubmittedAt: "2026-01-10T07:55:00.000Z",
  sessionCompletedAt: "2026-01-10T07:45:00.000Z",
  sessionStartedAt: "2026-01-10T07:05:00.000Z",
  secondAssignmentCreatedAt: "2026-02-01T00:00:00.000Z",
};

export const seedUser = {
  createdAt: seedTimestamps.createdAt,
  displayName: "Arnau",
  id: "user_arnau",
  status: "active" as const,
  updatedAt: seedTimestamps.createdAt,
};

export const seedExerciseCategories: SeedExerciseCategory[] = [
  {
    id: "cat_strength",
    name: "Strength",
    description:
      "Foundational resistance work tracked by sets, reps, and load.",
  },
  {
    id: "cat_mobility",
    name: "Mobility",
    description:
      "Joint prep and movement quality work used in warmups and cooldowns.",
  },
  {
    id: "cat_core",
    name: "Core",
    description: "Trunk stability and posture-focused accessory work.",
  },
  {
    id: "cat_conditioning",
    name: "Conditioning",
    description:
      "Aerobic and interval work meant to improve repeatable effort output.",
  },
];

export const seedExercises: SeedExercise[] = [
  {
    id: "exercise_goblet_squat",
    slug: "goblet-squat",
    name: "Goblet Squat",
    categoryId: "cat_strength",
    description:
      "A stable squat pattern that keeps setup simple for early progression.",
    instructions:
      "Hold one dumbbell at chest height, brace, sit between the hips, and stand without letting the chest collapse.",
    equipment: ["dumbbell", "bench"],
    trackingMode: "reps",
    difficulty: "beginner",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["core", "adductors"],
  },
  {
    id: "exercise_incline_push_up",
    slug: "incline-push-up",
    name: "Incline Push-Up",
    categoryId: "cat_strength",
    description:
      "Upper-body pressing with a scalable setup for consistent full range reps.",
    instructions:
      "Hands on a bench or box, body in a straight line, lower under control, then press back to full extension.",
    equipment: ["bench"],
    trackingMode: "reps",
    difficulty: "beginner",
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["front delts", "core"],
  },
  {
    id: "exercise_split_stance_row",
    slug: "split-stance-row",
    name: "Split Stance Dumbbell Row",
    categoryId: "cat_strength",
    description:
      "Single-arm pulling pattern for upper back strength and posture.",
    instructions:
      "Support one hand on a bench, keep hips square, and row the dumbbell to the lower ribs without twisting.",
    equipment: ["dumbbell", "bench"],
    trackingMode: "reps",
    difficulty: "beginner",
    primaryMuscles: ["lats", "mid-back"],
    secondaryMuscles: ["rear delts", "biceps"],
  },
  {
    id: "exercise_worlds_greatest_stretch",
    slug: "worlds-greatest-stretch",
    name: "World's Greatest Stretch",
    categoryId: "cat_mobility",
    description:
      "Dynamic mobility sequence covering hips, thoracic rotation, and hamstrings.",
    instructions:
      "Step into a long lunge, reach one arm up for rotation, switch sides deliberately, and keep breathing steady.",
    equipment: ["bodyweight"],
    trackingMode: "time",
    difficulty: "beginner",
    primaryMuscles: ["hips", "thoracic-spine"],
    secondaryMuscles: ["hamstrings", "shoulders"],
  },
  {
    id: "exercise_dead_bug",
    slug: "dead-bug",
    name: "Dead Bug",
    categoryId: "cat_core",
    description:
      "Core drill that teaches trunk stiffness and breathing under limb movement.",
    instructions:
      "Press lower back into the floor, move opposite arm and leg slowly, and reset before the spine loses contact.",
    equipment: ["bodyweight"],
    trackingMode: "reps",
    difficulty: "beginner",
    primaryMuscles: ["core"],
    secondaryMuscles: ["hip flexors", "shoulders"],
  },
  {
    id: "exercise_bike_intervals",
    slug: "bike-intervals",
    name: "Bike Intervals",
    categoryId: "cat_conditioning",
    description:
      "Stationary bike intervals used to build repeatable effort without impact.",
    instructions:
      "Alternate controlled recovery with higher-output efforts while keeping cadence smooth and breathing recoverable.",
    equipment: ["stationary-bike"],
    trackingMode: "mixed",
    difficulty: "beginner",
    primaryMuscles: ["cardiovascular-system", "quadriceps"],
    secondaryMuscles: ["glutes", "calves"],
  },
];

export const seedExerciseMedia: SeedExerciseMedia[] = [
  {
    id: "media_goblet_squat_image",
    exerciseId: "exercise_goblet_squat",
    type: "image",
    url: "/media/exercises/goblet-squat/front.svg",
    mimeType: "image/svg+xml",
    durationSeconds: null,
    thumbnailUrl: "/media/exercises/goblet-squat/front.svg",
    sortOrder: 1,
    createdAt: seedTimestamps.createdAt,
  },
  {
    id: "media_goblet_squat_side",
    exerciseId: "exercise_goblet_squat",
    type: "image",
    url: "/media/exercises/goblet-squat/side.svg",
    mimeType: "image/svg+xml",
    durationSeconds: null,
    thumbnailUrl: "/media/exercises/goblet-squat/side.svg",
    sortOrder: 2,
    createdAt: seedTimestamps.createdAt,
  },
  {
    id: "media_incline_push_up_image",
    exerciseId: "exercise_incline_push_up",
    type: "image",
    url: "/media/exercises/incline-push-up/front.svg",
    mimeType: "image/svg+xml",
    durationSeconds: null,
    thumbnailUrl: "/media/exercises/incline-push-up/front.svg",
    sortOrder: 1,
    createdAt: seedTimestamps.createdAt,
  },
  {
    id: "media_split_stance_row_image",
    exerciseId: "exercise_split_stance_row",
    type: "image",
    url: "/media/exercises/split-stance-row/front.svg",
    mimeType: "image/svg+xml",
    durationSeconds: null,
    thumbnailUrl: "/media/exercises/split-stance-row/front.svg",
    sortOrder: 1,
    createdAt: seedTimestamps.createdAt,
  },
  {
    id: "media_worlds_greatest_stretch_image",
    exerciseId: "exercise_worlds_greatest_stretch",
    type: "image",
    url: "/media/exercises/worlds-greatest-stretch/flow.svg",
    mimeType: "image/svg+xml",
    durationSeconds: null,
    thumbnailUrl: "/media/exercises/worlds-greatest-stretch/flow.svg",
    sortOrder: 1,
    createdAt: seedTimestamps.createdAt,
  },
  {
    id: "media_dead_bug_image",
    exerciseId: "exercise_dead_bug",
    type: "image",
    url: "/media/exercises/dead-bug/front.svg",
    mimeType: "image/svg+xml",
    durationSeconds: null,
    thumbnailUrl: "/media/exercises/dead-bug/front.svg",
    sortOrder: 1,
    createdAt: seedTimestamps.createdAt,
  },
  {
    id: "media_bike_intervals_image",
    exerciseId: "exercise_bike_intervals",
    type: "image",
    url: "/media/exercises/bike-intervals/dashboard.svg",
    mimeType: "image/svg+xml",
    durationSeconds: null,
    thumbnailUrl: "/media/exercises/bike-intervals/dashboard.svg",
    sortOrder: 1,
    createdAt: seedTimestamps.createdAt,
  },
];

export const seedWorkoutTemplates: SeedWorkoutTemplate[] = [
  {
    id: "template_foundation_a",
    slug: "foundation-a",
    name: "Foundation Session A",
    description:
      "Simple full-body baseline session for establishing quality movement patterns.",
    goal: "Baseline strength and movement quality",
    estimatedDurationMin: 35,
    difficulty: "beginner",
  },
  {
    id: "template_conditioning_reset",
    slug: "conditioning-reset",
    name: "Conditioning Reset",
    description:
      "Low-impact aerobic day with a short mobility opener and simple interval work.",
    goal: "Build aerobic tolerance without overwhelming recovery",
    estimatedDurationMin: 28,
    difficulty: "beginner",
  },
];

export const seedWorkoutTemplateExercises: SeedWorkoutTemplateExercise[] = [
  {
    id: "template_foundation_a_worlds_greatest_stretch",
    workoutTemplateId: "template_foundation_a",
    exerciseId: "exercise_worlds_greatest_stretch",
    sequence: 1,
    blockLabel: "warmup",
    instructionOverride:
      "Move continuously for the full interval and keep the transitions smooth.",
    targetSets: 1,
    targetReps: null,
    targetRepsMin: null,
    targetRepsMax: null,
    targetWeight: null,
    targetWeightUnit: null,
    targetDurationSeconds: 120,
    targetDistanceMeters: null,
    restSeconds: 30,
    tempo: null,
    rpeTarget: null,
    rirTarget: null,
    isOptional: false,
  },
  {
    id: "template_foundation_a_goblet_squat",
    workoutTemplateId: "template_foundation_a",
    exerciseId: "exercise_goblet_squat",
    sequence: 2,
    blockLabel: "main",
    instructionOverride:
      "Choose a load that leaves around two reps in reserve while staying upright.",
    targetSets: 3,
    targetReps: null,
    targetRepsMin: 8,
    targetRepsMax: 10,
    targetWeight: 18,
    targetWeightUnit: "kg",
    targetDurationSeconds: null,
    targetDistanceMeters: null,
    restSeconds: 90,
    tempo: "3-1-1",
    rpeTarget: 7,
    rirTarget: 2,
    isOptional: false,
  },
  {
    id: "template_foundation_a_incline_push_up",
    workoutTemplateId: "template_foundation_a",
    exerciseId: "exercise_incline_push_up",
    sequence: 3,
    blockLabel: "main",
    instructionOverride:
      "Raise the hands if needed to keep every rep strict and pain free.",
    targetSets: 3,
    targetReps: null,
    targetRepsMin: 8,
    targetRepsMax: 12,
    targetWeight: null,
    targetWeightUnit: null,
    targetDurationSeconds: null,
    targetDistanceMeters: null,
    restSeconds: 75,
    tempo: "2-1-1",
    rpeTarget: 7,
    rirTarget: 2,
    isOptional: false,
  },
  {
    id: "template_foundation_a_split_stance_row",
    workoutTemplateId: "template_foundation_a",
    exerciseId: "exercise_split_stance_row",
    sequence: 4,
    blockLabel: "main",
    instructionOverride:
      "Pause briefly at the top so the shoulder blade finishes the rep.",
    targetSets: 3,
    targetReps: null,
    targetRepsMin: 10,
    targetRepsMax: 12,
    targetWeight: 16,
    targetWeightUnit: "kg",
    targetDurationSeconds: null,
    targetDistanceMeters: null,
    restSeconds: 75,
    tempo: "2-1-2",
    rpeTarget: 7,
    rirTarget: 2,
    isOptional: false,
  },
  {
    id: "template_foundation_a_dead_bug",
    workoutTemplateId: "template_foundation_a",
    exerciseId: "exercise_dead_bug",
    sequence: 5,
    blockLabel: "cooldown",
    instructionOverride:
      "Slow each rep down and reset the breath between sides.",
    targetSets: 2,
    targetReps: null,
    targetRepsMin: 6,
    targetRepsMax: 8,
    targetWeight: null,
    targetWeightUnit: null,
    targetDurationSeconds: null,
    targetDistanceMeters: null,
    restSeconds: 30,
    tempo: null,
    rpeTarget: 6,
    rirTarget: 3,
    isOptional: false,
  },
  {
    id: "template_conditioning_reset_worlds_greatest_stretch",
    workoutTemplateId: "template_conditioning_reset",
    exerciseId: "exercise_worlds_greatest_stretch",
    sequence: 1,
    blockLabel: "warmup",
    instructionOverride:
      "Spend a little longer in the thoracic rotation on each side.",
    targetSets: 1,
    targetReps: null,
    targetRepsMin: null,
    targetRepsMax: null,
    targetWeight: null,
    targetWeightUnit: null,
    targetDurationSeconds: 90,
    targetDistanceMeters: null,
    restSeconds: 15,
    tempo: null,
    rpeTarget: null,
    rirTarget: null,
    isOptional: false,
  },
  {
    id: "template_conditioning_reset_bike_intervals",
    workoutTemplateId: "template_conditioning_reset",
    exerciseId: "exercise_bike_intervals",
    sequence: 2,
    blockLabel: "main",
    instructionOverride:
      "Treat the hard efforts as sustainable seven-out-of-ten efforts, not all-out sprints.",
    targetSets: 6,
    targetReps: null,
    targetRepsMin: null,
    targetRepsMax: null,
    targetWeight: null,
    targetWeightUnit: null,
    targetDurationSeconds: 60,
    targetDistanceMeters: 450,
    restSeconds: 60,
    tempo: null,
    rpeTarget: 7,
    rirTarget: null,
    isOptional: false,
  },
];

export const seedWorkoutAssignments: SeedWorkoutAssignment[] = [
  {
    id: "assignment_foundation_a",
    userId: seedUser.id,
    workoutTemplateId: "template_foundation_a",
    assignedBy: "fitnaista",
    startsOn: seedTimestamps.assignedOn,
    endsOn: null,
    scheduleNotes:
      "Repeat this session twice per week until the first real program lands.",
    frequencyPerWeek: 2,
    isActive: true,
    createdAt: seedTimestamps.createdAt,
    updatedAt: seedTimestamps.createdAt,
  },
  {
    id: "assignment_conditioning_reset",
    userId: seedUser.id,
    workoutTemplateId: "template_conditioning_reset",
    assignedBy: "fitnaista",
    startsOn: "2026-02-03",
    endsOn: "2026-03-03",
    scheduleNotes:
      "Use as a lighter day whenever recovery feels compressed after travel.",
    frequencyPerWeek: 1,
    isActive: false,
    createdAt: seedTimestamps.secondAssignmentCreatedAt,
    updatedAt: seedTimestamps.secondAssignmentCreatedAt,
  },
];

export const seedWorkoutSessions: SeedWorkoutSession[] = [
  {
    id: "session_foundation_a_2026_01_10",
    userId: seedUser.id,
    workoutTemplateId: "template_foundation_a",
    assignmentId: "assignment_foundation_a",
    status: "completed",
    startedAt: seedTimestamps.sessionStartedAt,
    completedAt: seedTimestamps.sessionCompletedAt,
    durationSeconds: 2400,
    performedVersionSnapshot: {
      templateId: "template_foundation_a",
      templateName: "Foundation Session A",
      exercises: [
        {
          id: "template_foundation_a_goblet_squat",
          targetSets: 3,
          targetRepsMin: 8,
          targetRepsMax: 10,
          targetWeight: 18,
          targetWeightUnit: "kg",
        },
        {
          id: "template_foundation_a_incline_push_up",
          targetSets: 3,
          targetRepsMin: 8,
          targetRepsMax: 12,
        },
      ],
    },
    notes:
      "Session moved well overall. Left one rep in reserve on the final row set.",
    createdAt: seedTimestamps.sessionStartedAt,
    updatedAt: seedTimestamps.sessionCompletedAt,
  },
  {
    id: "session_conditioning_reset_2026_02_12",
    userId: seedUser.id,
    workoutTemplateId: "template_conditioning_reset",
    assignmentId: "assignment_conditioning_reset",
    status: "abandoned",
    startedAt: "2026-02-12T18:10:00.000Z",
    completedAt: null,
    durationSeconds: 900,
    performedVersionSnapshot: {
      templateId: "template_conditioning_reset",
      templateName: "Conditioning Reset",
    },
    notes: "Stopped early when the bike console failed mid-session.",
    createdAt: "2026-02-12T18:10:00.000Z",
    updatedAt: "2026-02-12T18:25:00.000Z",
  },
];

export const seedExerciseSetLogs: SeedExerciseSetLog[] = [
  {
    id: "setlog_foundation_a_wgs_1",
    workoutSessionId: "session_foundation_a_2026_01_10",
    workoutTemplateExerciseId: "template_foundation_a_worlds_greatest_stretch",
    exerciseId: "exercise_worlds_greatest_stretch",
    sequence: 1,
    setNumber: 1,
    performedReps: null,
    performedWeight: null,
    performedWeightUnit: null,
    performedDurationSeconds: 120,
    performedDistanceMeters: null,
    restSecondsActual: 25,
    rpe: 4,
    completed: true,
    notes: null,
    loggedAt: "2026-01-10T07:09:30.000Z",
  },
  {
    id: "setlog_foundation_a_goblet_1",
    workoutSessionId: "session_foundation_a_2026_01_10",
    workoutTemplateExerciseId: "template_foundation_a_goblet_squat",
    exerciseId: "exercise_goblet_squat",
    sequence: 2,
    setNumber: 1,
    performedReps: 10,
    performedWeight: 18,
    performedWeightUnit: "kg",
    performedDurationSeconds: null,
    performedDistanceMeters: null,
    restSecondsActual: 90,
    rpe: 7,
    completed: true,
    notes: null,
    loggedAt: "2026-01-10T07:16:00.000Z",
  },
  {
    id: "setlog_foundation_a_goblet_2",
    workoutSessionId: "session_foundation_a_2026_01_10",
    workoutTemplateExerciseId: "template_foundation_a_goblet_squat",
    exerciseId: "exercise_goblet_squat",
    sequence: 2,
    setNumber: 2,
    performedReps: 9,
    performedWeight: 18,
    performedWeightUnit: "kg",
    performedDurationSeconds: null,
    performedDistanceMeters: null,
    restSecondsActual: 92,
    rpe: 7,
    completed: true,
    notes: null,
    loggedAt: "2026-01-10T07:20:10.000Z",
  },
  {
    id: "setlog_foundation_a_push_up_1",
    workoutSessionId: "session_foundation_a_2026_01_10",
    workoutTemplateExerciseId: "template_foundation_a_incline_push_up",
    exerciseId: "exercise_incline_push_up",
    sequence: 3,
    setNumber: 1,
    performedReps: 12,
    performedWeight: null,
    performedWeightUnit: null,
    performedDurationSeconds: null,
    performedDistanceMeters: null,
    restSecondsActual: 70,
    rpe: 7,
    completed: true,
    notes: null,
    loggedAt: "2026-01-10T07:27:05.000Z",
  },
  {
    id: "setlog_foundation_a_row_1",
    workoutSessionId: "session_foundation_a_2026_01_10",
    workoutTemplateExerciseId: "template_foundation_a_split_stance_row",
    exerciseId: "exercise_split_stance_row",
    sequence: 4,
    setNumber: 1,
    performedReps: 12,
    performedWeight: 16,
    performedWeightUnit: "kg",
    performedDurationSeconds: null,
    performedDistanceMeters: null,
    restSecondsActual: 75,
    rpe: 8,
    completed: true,
    notes: "Last two reps slowed slightly but stayed clean.",
    loggedAt: "2026-01-10T07:34:15.000Z",
  },
];

export const seedWorkoutFeedback: SeedWorkoutFeedback[] = [
  {
    id: "feedback_foundation_a_2026_01_10",
    workoutSessionId: "session_foundation_a_2026_01_10",
    userId: seedUser.id,
    mood: "steady",
    difficultyRating: 7,
    energyRating: 4,
    painFlag: false,
    painNotes: null,
    freeText:
      "Squats felt stable. Push-ups are ready to progress lower next week.",
    submittedAt: seedTimestamps.feedbackSubmittedAt,
  },
];
